#!/bin/bash

CWD="${BASH_SOURCE[0]}"

source "${CWD}/variables.sh"
source "${CWD}/folders.sh"
ln -fsv "${CWD}/variables.sh" "${XDG_CONFIG_HOME}/XDG/variables.sh"
ln -fsv "${CWD}/xdg" "${XDG_BIN_HOME}"

sudo ln -fsv "${CWD}/variables.sh" /etc/profile.d

unset CWD
