#!/bin/bash

CWD="$(szh realpath "${0}")"

source "${CWD}/variables.sh"
source "${CWD}/folders.sh"
ln -fsv "${CWD}/variables.sh" "${XDG_CONFIG_HOME}/XDG/variables.sh"

sudo ln -fsv "${CWD}/variables.sh" /etc/profile.d

unset CWD
