#!/bin/bash

m_flag=false
p_flag=false

while getopts 'hmp' flag; do
    case "${flag}" in
        m) m_flag=true ;;
        p) p_flag=true ;;
        *) szh usage '[-h(elp)m(igrate)p(rompt)]' || exit ;;
    esac
done

CWD="$(szh realpath "${0}")/packages"

if [[ "${m_flag}" = true ]]; then
    for package in $(szh find -c "${CWD}") ; do
        source "${CWD}/${package}"
    done
fi

if [[ "${p_flag}" = true ]]; then
    szh prompt -s 'Would you like XDG variables be sourced automatically from .bashrc? (If not, source files from ~/.config/XDG manually)'
    echo "source ${XDG_CONFIG_HOME}/XDG/variables.sh" >> ~/.bashrc
    echo "source ${XDG_CONFIG_HOME}/XDG/packages.sh" >> ~/.bashrc
fi
